/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_ui_taf_tutorial_2025;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
